id = "inform6"
name = "Inform 6"
version = "1.0.0"
schema_version = 1
authors = ["Sam Win-Mason <sam@albedogames.com>"]
description = "Zed language support for the Inform 6 programming language."
repository = "https://github.com/Or4c/zed-inform6"

[grammars.inform6]
repository = "https://github.com/Or4c/tree-sitter-inform6"
commit = "0cccc03dfbb9b39fa79a4c0593105ebf98bdb4e3"
